import { useState, type FormEvent, type ReactNode } from "react";
import * as Accordion from "@radix-ui/react-accordion";
import { ChevronDown, Menu, X } from "lucide-react";
import { z } from "zod";
import { site, whatsappUrl } from "@/content/site";
import { CareIcon, GraduationIcon, LocationIcon, ShieldIcon, dentalIcons } from "@/components/DentalIcons";

const sectionClass = "section-space";

export function Header() {
  const [open, setOpen] = useState(false);
  return <header className="site-header"><div className="site-container header-inner"><a className="brand" href="#top" aria-label={site.name}><img src={site.logoImage} alt={site.name} /></a><nav className="desktop-nav" aria-label="Navegação principal">{site.nav.map((item) => <a key={item.href} href={item.href}>{item.label}</a>)}<a className="button button-small" href="#agendar">{site.ctas.schedule}</a></nav><button className="menu-button" type="button" aria-label="Abrir menu" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div>{open && <nav className="mobile-nav" aria-label="Navegação principal">{site.nav.map((item) => <a key={item.href} href={item.href} onClick={() => setOpen(false)}>{item.label}</a>)}<a href="#agendar" onClick={() => setOpen(false)}>{site.ctas.schedule}</a></nav>}</header>;
}
export function HeroSection() { return <section id="top" className="hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(20,58,92,.82), rgba(20,58,92,.62)), url(${site.hero.image})` }}><div className="site-container hero-content"><p className="hero-name">{site.name}<span className="hero-cro">{site.cro}</span></p><h1>{site.hero.title}</h1>{site.hero.paragraphs.map((p) => <p key={p}>{p}</p>)}<div className="button-row"><a className="button button-accent" href={whatsappUrl()} target="_blank" rel="noreferrer">{site.ctas.schedule}</a><a className="button button-outline-light" href="#sobre">{site.ctas.knowDoctor}</a></div></div></section>; }
export function AboutSection() { return <section id="sobre" className={sectionClass}><div className="site-container about-grid"><div className="portrait-wrap"><img src={site.about.image} alt={site.name} /></div><div><h2>{site.about.title}</h2>{site.about.paragraphs.map((p) => <p key={p}>{p}</p>)}<h3>{site.about.credentialsTitle}</h3><ul className="credentials">{site.about.credentials.map((item) => <li key={item}><GraduationIcon/><span>{item}</span></li>)}</ul><span className="badge">{site.cro}</span></div></div></section>; }
export function DifferentialsSection() { const icons = [CareIcon, ShieldIcon, GraduationIcon, CareIcon]; return <section className="differentials" aria-label="Diferenciais"><div className="site-container value-grid">{site.differentials.map((item, index) => { const Icon = icons[index]; return <div className="value" key={item}><Icon/><p>{item}</p></div>; })}</div></section>; }
export function AreasSection() { return <section id="areas" className={`${sectionClass} offwhite`}><div className="site-container"><div className="section-heading"><h2>{site.areas.title}</h2><p>{site.areas.intro}</p></div><div className="area-grid">{site.areas.items.map((item) => { const Icon = dentalIcons[item.icon]; return <article className={`area-card ${"urgency" in item ? "area-urgent" : ""}`} key={item.title}><Icon/><div><h3>{item.title}</h3><p>{item.text}</p></div></article>; })}</div></div></section>; }
export function UrgencySection() { return <section className="urgency-block"><div className="site-container urgency-inner"><div><h2>{site.urgency.title}</h2><p>{site.urgency.text}</p></div><a className="button button-accent" href={whatsappUrl(site.urgencyMessage)} target="_blank" rel="noreferrer">{site.ctas.urgency}</a></div></section>; }
export function BenefitsSection() { return <section className={sectionClass}><div className="site-container"><div className="section-heading"><h2>{site.benefits.title}</h2></div><div className="benefit-grid">{site.benefits.items.map((item) => { const Icon = dentalIcons[item.icon]; return <article key={item.title}><Icon/><div><h3>{item.title}</h3><p>{item.text}</p></div></article>; })}</div></div></section>; }
export function ClinicSection() { return <section id="clinica" className={`${sectionClass} offwhite`}><div className="site-container"><div className="clinic-copy"><h2>{site.clinic.title}</h2><p>{site.clinic.text}</p><div className="clinic-detail"><LocationIcon/><div><strong>{site.clinic.addressLabel}</strong><p>{site.address}</p><strong>{site.clinic.hoursLabel}</strong><p>{site.hours}</p><a href={site.mapsUrl} target="_blank" rel="noreferrer">{site.clinic.mapsLabel}</a></div></div></div><div className="gallery">{site.clinic.images.map((image) => <img key={image.src} src={image.src} alt={image.alt} loading="lazy" />)}</div></div></section>; }
export function TestimonialsSection() { return <section className={sectionClass}><div className="site-container section-heading"><h2>{site.testimonials.title}</h2><p>{site.testimonials.intro}</p><div className="testimonial-placeholder"><p>{site.testimonials.empty}</p></div></div></section>; }
export function FinalCtaSection() { return <section className="final-cta"><div className="site-container"><span className="cta-icon" aria-hidden="true"><img src={site.iconImage} alt="" /></span><h2>{site.finalCta.title}</h2><p>{site.finalCta.text}</p><a className="button button-accent" href={whatsappUrl()} target="_blank" rel="noreferrer">{site.ctas.whatsapp}</a><small>{site.finalCta.note}</small></div></section>; }
export function FaqSection() { return <section id="faq" className={sectionClass}><div className="site-container faq-wrap"><div className="section-heading"><h2>FAQ</h2></div><Accordion.Root className="accordion" type="single" collapsible>{site.faq.map((item) => <Accordion.Item className="accordion-item" value={item.question} key={item.question}><Accordion.Header><Accordion.Trigger className="accordion-trigger">{item.question}<ChevronDown aria-hidden="true"/></Accordion.Trigger></Accordion.Header><Accordion.Content className="accordion-content"><p>{item.answer}</p></Accordion.Content></Accordion.Item>)}</Accordion.Root></div></section>; }

const formSchema = z.object({ name: z.string().trim().min(1, "Informe seu nome."), phone: z.string().trim().min(1, "Informe seu telefone."), whatsapp: z.string().trim().min(1, "Informe seu WhatsApp."), email: z.string().trim().email("Informe um e-mail válido."), region: z.string().trim().min(1, "Informe seu bairro/região."), path: z.enum(["Urgência", "Implante ou prótese", "Estética", "Ortodontia"], { required_error: "Escolha uma opção." }), message: z.string().optional() });
type FormData = z.infer<typeof formSchema>;
const emptyForm = { name: "", phone: "", whatsapp: "", email: "", region: "", path: "", message: "" };
export function ContactFormSection() {
  const [values, setValues] = useState(emptyForm); const [errors, setErrors] = useState<Record<string, string>>({});
  const update = (field: keyof typeof values, value: string) => setValues((current) => ({ ...current, [field]: value }));
  const submit = (event: FormEvent) => { event.preventDefault(); const parsed = formSchema.safeParse(values); if (!parsed.success) { const next: Record<string, string> = {}; parsed.error.issues.forEach((issue) => { next[String(issue.path[0])] = issue.message; }); setErrors(next); return; } setErrors({}); const data: FormData = parsed.data; const message = `Olá! Vim pelo site do Dr. Germano. Busco: ${data.path}. Nome: ${data.name}. Telefone: ${data.phone}. WhatsApp: ${data.whatsapp}. E-mail: ${data.email}. Bairro/região: ${data.region}.${data.message ? ` Mensagem: ${data.message}` : ""}`; window.location.href = whatsappUrl(message); };
  return <section id="agendar" className={`${sectionClass} offwhite`}><div className="site-container form-wrap"><div className="section-heading"><h2>{site.form.title}</h2></div><form onSubmit={submit} noValidate><div className="form-grid">{(["name", "phone", "whatsapp", "email", "region"] as const).map((field) => <FormField key={field} label={site.form.fields[field]} error={errors[field]}><input type={field === "email" ? "email" : field === "name" || field === "region" ? "text" : "tel"} value={values[field]} onChange={(e) => update(field, e.target.value)} aria-invalid={!!errors[field]} /></FormField>)}<FormField label={site.form.fields.path} error={errors.path}><select value={values.path} onChange={(e) => update("path", e.target.value)} aria-invalid={!!errors.path}><option value="" disabled>{site.form.fields.path}</option>{site.form.options.map((option) => <option key={option}>{option}</option>)}</select></FormField></div><FormField label={site.form.fields.message} error={errors.message}><textarea rows={4} value={values.message} onChange={(e) => update("message", e.target.value)} /></FormField><button className="button" type="submit">{site.form.submit}</button></form></div></section>;
}
function FormField({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="field"><span>{label}</span>{children}{error && <small role="alert">{error}</small>}</label>; }
export function Footer() { return <footer><div className="site-container footer-grid"><img src={site.footer.logo} alt={site.footer.institute}/><div><strong>{site.footer.institute}</strong><p>{site.address}</p><p>{site.cro}</p></div><p>© {new Date().getFullYear()} {site.name}. {site.footer.rights}</p></div></footer>; }
